version: "3.9"  # optional since v1.27.0
services:
  backend:
    build: "."
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: water_gallery
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./env/docker/db:/var/lib/mysql
    ports:
      - "3306:3306"
