server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-z1noh6-s.auth0.com/
          jwk-set-uri: https://dev-z1noh6-s.auth0.com/.well-known/jwks.json
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/water_gallery?useUnicode=true&useJDBCCompliantTimezoneShift=false&serverTimezone=UTC
    username: root
    password: password
  flyway:
    user: root
    password: password
    url: jdbc:mysql://localhost:3306/water_gallery?useUnicode=true&useJDBCCompliantTimezoneShift=false&serverTimezone=UTC
    locations: classpath:db/migration
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
