version: 3.9
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: v1-mvn-cache-{{ checksum "pom.xml" }}
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: test & build
          command: ./mvnw clean package
      - run:
          name: docker build image
          command: docker build --tag latest
      - run:
          name: image push
          command: docker push <hub-user>/<repo-name>:<tag>
      - save_cache:
          paths:
            - ~/.mvn/wrapper
          key: v1-mvn-wrapper-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    -
