version: 3.9
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: v1-mvn-cache-{{ checksum "pom.xml" }}
      - run:
          name: Install dependencies
          command: ./mvnw clean package
      - save_cache:
          paths:
            - ~/.mvn/wrapper
          key: v1-mvn-wrapper-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    -
